### ISSUE TITLE
Ubuntu 9.04: cannot open shared object file

### ISSUE THREAD

**Issue by hannakalinowska** [adamsanderson/ruby_scope#2]
I'm getting the following error when I try running `ruby_scope`:

```
/usr/local/lib/ruby/1.8/x86_64-linux/dbm.so: libdb-4.6.so: cannot open shared object file: No such file or directory - /usr/local/lib/ruby/1.8/x86_64-linux/dbm.so (LoadError)
        from /usr/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
        from ./bin/../lib/ruby_scope/sexp_cache.rb:1
        from /usr/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
        from /usr/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
        from ./bin/../lib/ruby_scope.rb:19
        from ./bin/../lib/ruby_scope.rb:16:in `each'
        from ./bin/../lib/ruby_scope.rb:16
        from bin/ruby_scope:3:in `require'
        from bin/ruby_scope:3
```

Any ideas?

**Comment by adamsanderson** [comment]
Looks like it's a problem loading the cache.

You could try two things, either try installing dbm if it isn't installed (I was under the impression it was pretty common on ruby installs).  Otherwise you could try switching the library requirement from 'dbm' to 'gdbm' and then changing DB = DBM to DB = GDBM.  I don't have that available, so I really don't know if it would work.

Alternatively if you have a suggestion for a lightweight way to cache data, I'd be all for it ;)

**Comment by hannakalinowska** [comment]
So sorry to leave it hanging for so long. I now upgraded to Ubuntu 10.04 but I still have this problem. The library is there, in  /usr/local/lib/ruby/1.8/x86_64-linux/dbm.so. Don't know if it changes anything but I'm using Ruby Enterprise Edition 1.8.7.

**Comment by adamsanderson** [comment]
To be entirely honest, I have no idea.  Perhaps I can give it a shot on my other machine.  I've been getting an Ubuntu box set up, but I don't really develop on it much.
